### PR TITLE
Implement unary `-`

### PR DESCRIPTION
**Pull request by yutannihilation**
Currently, this code

```rs
fn dsp() {
    2.0-2.0
}
```

cannot be parsed.

```
Filename: \\?\C:\Users\Yutani\Documents\GitHub\mimium-rs\tmp.mmm
, ror: unexpected token something else, expected ^, ;,
, (, |, -, /, ", :, *, <, !, =, 0, ., +, }, [, ), %, ,, &, {, ], >
   ╭─[\\?\C:\Users\Yutani\Documents\GitHub\mimium-rs\tmp.mmm:2:3]
   │
 2 │     2.0-2.0
   ·   ┬
   ·   ╰── Unexpected token
───╯
Error: unexpected token while parsing apply, expected ||, linebreak, }, |>, >, -, <=, +, !=, /, ;, >=, &&, %, (, ==, <, *, ^
   ╭─[\\?\C:\Users\Yutani\Documents\GitHub\mimium-rs\tmp.mmm:2:8]
   │
 2 │     2.0-2.0
   ·        ──┬─
   ·          ╰─── Unexpected token -2.0
───╯
```

This is because there's no parser for unary operations. Currently, the lexer parses `-` as part of a float literal.

https://github.com/tomoyanonymous/mimium-rs/blob/ee0ed1a0cc5c3c8902bf95990d3209f2645e888d/mimium-lang/src/compiler/parser/lexer.rs#L24-L30

It might be a choice to require spaces before and after `-` to distinguish the binary op and the unary op. But, I think users expect this syntax is valid, so mimium anyway needs a unary parser.

```rs
-x
```

### CODE REVIEW

**Comment by tomoyanonymous** [comment]
Thanks! Maybe should we add more test cases with nested operation to ensure the parse works correctly?
```rust
    run_simple_test("- -1.0", 1.0, 3);
    run_simple_test("-(-hoge)", 2.0, 3);
```

**Comment by yutannihilation** [comment]
Thanks. Sure, I'll add some more test cases.

**Comment by yutannihilation** [comment]
It seems a function call like this is not handled properly, so my implementation is not correct. Let me think.

```rs
-cos(0.0)
```

**Comment by tomoyanonymous** [comment]
Now parser emits ast for `-cos(0.0)` to `(app (app neg (cos))((float 0.0))))`. (`(- cos) (0.0)`)
(You can emit raw ast as lisp-like syntax with `--emit-ast` option )

Now precedence of `unary` operator is bigger than `apply`. It should be just in between `apply` and other binary operators.

**Comment by yutannihilation** [comment]
> Now precedence of `unary` operator is bigger than `apply`. It should be just in between `apply` and other binary operators.

You are right, thanks. Should be fixed now!

**Pull request merged**
